server:
  port: 5000
  servlet:
    context-path: /

spring:
  application:
    name: modular-address-book
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.addressbook: INFO
    org.springframework: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 